### ISSUE TITLE
Issues with Text and Layout on Login Page

### ISSUE THREAD

**Issue by Pragati1466** [ankit071105/Ticket-Booking#280]
### Description

The login page contains several layout and text issues that affect user experience:

1.The greeting should say "Welcome back!" instead of "Welcome! Back".
2.The section "Don't Have an Account?" and the subsequent "Register" and "Log In" options are not properly aligned.
3.The "Log In" button is not contained within a proper box or background color, making it feel disconnected from the rest of the page, while the "Welcome" section has a grey background that keeps it visually cohesive.

### Screenshots

<img width="730" alt="Screen Shot 2024-10-09 at 6 29 55 PM" src="https://github.com/user-attachments/assets/2e359f6e-84e1-425f-b004-36dc28d9f2ae">

### Any additional information?

 A well-structured layout with consistent text and button styling will improve the user experience and make navigation clearer.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Pragati1466** [comment]
I would like to work on it under GSSoC'24 and Hacktoberfest 2024 @ankit071105

**Comment by ankit071105** [comment]
it has been resolved

**Comment by Pragati1466** [comment]
But i found it first then why was i not assigned

**Comment by Pragati1466** [comment]
I think its violating the conduct policy a bit please see to it from next time i will be highly grateful to you

**Comment by Pragati1466** [comment]
and by the way issue is still not resolved and now ui is even more worsened 
<img width="1784" alt="Screen Shot 2024-10-19 at 11 28 51 @ankit071105 rc="https://github.com/user-attachments/assets/3680b130-64de-4d8b-aaab-d05ce536fc43">
@ankit071105

**Comment by Pragati1466** [comment]
<img width="1784" alt="Screen Shot 2024-10-19 at 11 28 51 AM" src="https://github.com/user-attachments/assets/40f6211e-7198-4dfa-878d-7db91f782265">

**Comment by ankit071105** [comment]
> I think its violating the conduct policy a bit please see to it from next time i will be highly grateful to you

no i have assigned this issue 3 days before and today PR i have recieved We all follow guidelines ...You should see all the issues first then you can generate your issue

**Comment by ankit071105** [comment]
> > I think its violating the conduct policy a bit please see to it from next time i will be highly grateful to you
> 
> no i have assigned this issue 3 days before and today PR i have recieved We all follow guidelines ...You should see all the issues first then you can generate your issue

@Pragati1466

**Comment by Pragati1466** [comment]
my issue number is 280 is it befote that?? and i opened a week ago

**Comment by ankit071105** [comment]
You have any soultion for this show me some ss or video if i will be good then i will assign you okay @Pragati1466

**Comment by Pragati1466** [comment]
yes sure
